// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           20
// Async Callback:                       1
// Total number of exported functions:  22

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xn_main
    (
        issue_token
        register_or_renew
        update_primary_address
        update_key_value
        accept
        revoke_accept_request
        set_reservations
        clear_reservations
        update_price_usd
        fetch_egld_usd_prices
        get_reservation
        getNftTokenId
        get_accept_request
        get_domain_name
        get_owner_domain_name
        resolve
        resolve_domain_name_key
        get_prices_usd
        get_egld_usd_price
        get_allowed_top_level_domains
        callBack
    )
}
